<?php

use Illuminate\Database\Seeder;
use Vape\Celeb;

class CelebsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Celeb::create(["name"=>"50 Cent","img"=>"https://www.randomlists.com/img/people/50_cent.jpg"]);
        Celeb::create(["name"=>"Abraham","img"=>"https://www.randomlists.com/img/people/abraham.jpg"]);
        Celeb::create(["name"=>"Abraham Lincoln","img"=>"https://www.randomlists.com/img/people/abraham_lincoln.jpg"]);
        Celeb::create(["name"=>"Adam Sandler","img"=>"https://www.randomlists.com/img/people/adam_sandler.jpg"]);
        Celeb::create(["name"=>"Albert Einstein","img"=>"https://www.randomlists.com/img/people/albert_einstein.jpg"]);
        Celeb::create(["name"=>"Alec Baldwin","img"=>"https://www.randomlists.com/img/people/alec_baldwin.jpg"]);
        Celeb::create(["name"=>"Alex Rodriguez","img"=>"https://www.randomlists.com/img/people/alex_rodriguez.jpg"]);
        Celeb::create(["name"=>"Alexander the Great","img"=>"https://www.randomlists.com/img/people/alexander_the_great.jpg"]);
        Celeb::create(["name"=>"Amelia Earhart","img"=>"https://www.randomlists.com/img/people/amelia_earhart.jpg"]);
        Celeb::create(["name"=>"Angelina Jolie","img"=>"https://www.randomlists.com/img/people/angelina_jolie.jpg"]);
        Celeb::create(["name"=>"Anne Frank","img"=>"https://www.randomlists.com/img/people/anne_frank.jpg"]);
        Celeb::create(["name"=>"Anne Hathaway","img"=>"https://www.randomlists.com/img/people/anne_hathaway.jpg"]);
        Celeb::create(["name"=>"Aristotle","img"=>"https://www.randomlists.com/img/people/aristotle.jpg"]);
        Celeb::create(["name"=>"Arnold Schwarzenegger","img"=>"https://www.randomlists.com/img/people/arnold_schwarzenegger.jpg"]);
        Celeb::create(["name"=>"Audrey Hepburn","img"=>"https://www.randomlists.com/img/people/audrey_hepburn.jpg"]);
        Celeb::create(["name"=>"Augustus","img"=>"https://www.randomlists.com/img/people/augustus.jpg"]);
        Celeb::create(["name"=>"Babe Ruth","img"=>"https://www.randomlists.com/img/people/babe_ruth.jpg"]);
        Celeb::create(["name"=>"Barack Obama","img"=>"https://www.randomlists.com/img/people/barack_obama.jpg"]);
        Celeb::create(["name"=>"Barbra Streisand","img"=>"https://www.randomlists.com/img/people/barbra_streisand.jpg"]);
        Celeb::create(["name"=>"Ben Stiller","img"=>"https://www.randomlists.com/img/people/ben_stiller.jpg"]);
        Celeb::create(["name"=>"Benjamin Franklin","img"=>"https://www.randomlists.com/img/people/benjamin_franklin.jpg"]);
        Celeb::create(["name"=>"Bethenny Frankel","img"=>"https://www.randomlists.com/img/people/bethenny_frankel.jpg"]);
        Celeb::create(["name"=>"Beyoncé","img"=>"https://www.randomlists.com/img/people/beyonc_.jpg"]);
        Celeb::create(["name"=>"Bill Cosby","img"=>"https://www.randomlists.com/img/people/bill_cosby.jpg"]);
        Celeb::create(["name"=>"Bill Gates","img"=>"https://www.randomlists.com/img/people/bill_gates.jpg"]);
        Celeb::create(["name"=>"Billy Graham","img"=>"https://www.randomlists.com/img/people/billy_graham.jpg"]);
        Celeb::create(["name"=>"Bob Dylan","img"=>"https://www.randomlists.com/img/people/bob_dylan.jpg"]);
        Celeb::create(["name"=>"Bob Hope","img"=>"https://www.randomlists.com/img/people/bob_hope.jpg"]);
        Celeb::create(["name"=>"Bob Marley","img"=>"https://www.randomlists.com/img/people/bob_marley.jpg"]);
        Celeb::create(["name"=>"John Bon Jovi","img"=>"https://www.randomlists.com/img/people/john_bon_jovi.jpg"]);
        Celeb::create(["name"=>"Booker T. Washington","img"=>"https://www.randomlists.com/img/people/booker_t_washington.jpg"]);
        Celeb::create(["name"=>"Brad Paisley","img"=>"https://www.randomlists.com/img/people/brad_paisley.jpg"]);
        Celeb::create(["name"=>"Brad Pitt","img"=>"https://www.randomlists.com/img/people/brad_pitt.jpg"]);
        Celeb::create(["name"=>"Brian Grazer","img"=>"https://www.randomlists.com/img/people/brian_grazer.jpg"]);
        Celeb::create(["name"=>"Britney Spears","img"=>"https://www.randomlists.com/img/people/britney_spears.jpg"]);
        Celeb::create(["name"=>"Bruce Lee","img"=>"https://www.randomlists.com/img/people/bruce_lee.jpg"]);
        Celeb::create(["name"=>"Bruce Springsteen","img"=>"https://www.randomlists.com/img/people/bruce_springsteen.jpg"]);
        Celeb::create(["name"=>"Buddha","img"=>"https://www.randomlists.com/img/people/buddha.jpg"]);
        Celeb::create(["name"=>"C. S. Lewis","img"=>"https://www.randomlists.com/img/people/c_s_lewis.jpg"]);
        Celeb::create(["name"=>"Cameron Diaz","img"=>"https://www.randomlists.com/img/people/cameron_diaz.jpg"]);
        Celeb::create(["name"=>"Carl Sagan","img"=>"https://www.randomlists.com/img/people/carl_sagan.jpg"]);
        Celeb::create(["name"=>"Carrie Underwood","img"=>"https://www.randomlists.com/img/people/carrie_underwood.jpg"]);
        Celeb::create(["name"=>"Catherine Zeta-Jones","img"=>"https://www.randomlists.com/img/people/catherine_zeta_jones.jpg"]);
        Celeb::create(["name"=>"Catherine, Duchess of Cambridge","img"=>"https://www.randomlists.com/img/people/catherine_duchess_of_cambridge.jpg"]);
        Celeb::create(["name"=>"Charles Darwin","img"=>"https://www.randomlists.com/img/people/charles_darwin.jpg"]);
        Celeb::create(["name"=>"Charlie Sheen","img"=>"https://www.randomlists.com/img/people/charlie_sheen.jpg"]);
        Celeb::create(["name"=>"Che Guevara","img"=>"https://www.randomlists.com/img/people/che_guevara.jpg"]);
        Celeb::create(["name"=>"Chief Sitting Bull","img"=>"https://www.randomlists.com/img/people/chief_sitting_bull.jpg"]);
        Celeb::create(["name"=>"Chris Rock","img"=>"https://www.randomlists.com/img/people/chris_rock.jpg"]);
        Celeb::create(["name"=>"Christopher Nolan","img"=>"https://www.randomlists.com/img/people/christopher_nolan.jpg"]);
        Celeb::create(["name"=>"Chuck Lorre","img"=>"https://www.randomlists.com/img/people/chuck_lorre.jpg"]);
        Celeb::create(["name"=>"Clint Eastwood","img"=>"https://www.randomlists.com/img/people/clint_eastwood.jpg"]);
        Celeb::create(["name"=>"Coco Chanel","img"=>"https://www.randomlists.com/img/people/coco_chanel.jpg"]);
        Celeb::create(["name"=>"Colin Powell","img"=>"https://www.randomlists.com/img/people/colin_powell.jpg"]);
        Celeb::create(["name"=>"Confucius","img"=>"https://www.randomlists.com/img/people/confucius.jpg"]);
        Celeb::create(["name"=>"Courteney Cox","img"=>"https://www.randomlists.com/img/people/courteney_cox.jpg"]);
        Celeb::create(["name"=>"Cristiano Ronaldo","img"=>"https://www.randomlists.com/img/people/cristiano_ronaldo.jpg"]);
        Celeb::create(["name"=>"Danica Patrick","img"=>"https://www.randomlists.com/img/people/danica_patrick.jpg"]);
        Celeb::create(["name"=>"Daniel Boone","img"=>"https://www.randomlists.com/img/people/daniel_boone.jpg"]);
        Celeb::create(["name"=>"Daniel Radcliffe","img"=>"https://www.randomlists.com/img/people/daniel_radcliffe.jpg"]);
        Celeb::create(["name"=>"Danielle Steel","img"=>"https://www.randomlists.com/img/people/danielle_steel.jpg"]);
        Celeb::create(["name"=>"Dave Matthews","img"=>"https://www.randomlists.com/img/people/dave_matthews.jpg"]);
        Celeb::create(["name"=>"David Beckham","img"=>"https://www.randomlists.com/img/people/david_beckham.jpg"]);
        Celeb::create(["name"=>"David Copperfield","img"=>"https://www.randomlists.com/img/people/david_copperfield.jpg"]);
        Celeb::create(["name"=>"David Letterman","img"=>"https://www.randomlists.com/img/people/david_letterman.jpg"]);
        Celeb::create(["name"=>"Demi Lovato","img"=>"https://www.randomlists.com/img/people/demi_lovato.jpg"]);
        Celeb::create(["name"=>"Denzel Washington","img"=>"https://www.randomlists.com/img/people/denzel_washington.jpg"]);
        Celeb::create(["name"=>"Derek Jeter","img"=>"https://www.randomlists.com/img/people/derek_jeter.jpg"]);
        Celeb::create(["name"=>"Diana, Princess of Wales","img"=>"https://www.randomlists.com/img/people/diana_princess_of_wales.jpg"]);
        Celeb::create(["name"=>"Dick Wolf","img"=>"https://www.randomlists.com/img/people/dick_wolf.jpg"]);
        Celeb::create(["name"=>"Donald Trump","img"=>"https://www.randomlists.com/img/people/donald_trump.jpg"]);
        Celeb::create(["name"=>"Drew Barrymore","img"=>"https://www.randomlists.com/img/people/drew_barrymore.jpg"]);
        Celeb::create(["name"=>"Dwayne Wade","img"=>"https://www.randomlists.com/img/people/dwayne_wade.jpg"]);
        Celeb::create(["name"=>"Dwight Howard","img"=>"https://www.randomlists.com/img/people/dwight_howard.jpg"]);
        Celeb::create(["name"=>"Eddie Murphy","img"=>"https://www.randomlists.com/img/people/eddie_murphy.jpg"]);
        Celeb::create(["name"=>"Edgar Allan Poe","img"=>"https://www.randomlists.com/img/people/edgar_allan_poe.jpg"]);
        Celeb::create(["name"=>"Eleanor Roosevelt","img"=>"https://www.randomlists.com/img/people/eleanor_roosevelt.jpg"]);
        Celeb::create(["name"=>"Ellen DeGeneres","img"=>"https://www.randomlists.com/img/people/ellen_degeneres.jpg"]);
        Celeb::create(["name"=>"Elton John","img"=>"https://www.randomlists.com/img/people/elton_john.jpg"]);
        Celeb::create(["name"=>"Elvis Presley","img"=>"https://www.randomlists.com/img/people/elvis_presley.jpg"]);
        Celeb::create(["name"=>"Emeril Lagasse","img"=>"https://www.randomlists.com/img/people/emeril_lagasse.jpg"]);
        Celeb::create(["name"=>"Eminem","img"=>"https://www.randomlists.com/img/people/eminem.jpg"]);
        Celeb::create(["name"=>"Emma Watson","img"=>"https://www.randomlists.com/img/people/emma_watson.jpg"]);
        Celeb::create(["name"=>"Ernest Hemingway","img"=>"https://www.randomlists.com/img/people/ernest_hemingway.jpg"]);
        Celeb::create(["name"=>"Eva Longoria","img"=>"https://www.randomlists.com/img/people/eva_longoria.jpg"]);
        Celeb::create(["name"=>"Fidel Castro","img"=>"https://www.randomlists.com/img/people/fidel_castro.jpg"]);
        Celeb::create(["name"=>"Frank Zappa","img"=>"https://www.randomlists.com/img/people/frank_zappa.jpg"]);
        Celeb::create(["name"=>"Franklin D. Roosevelt","img"=>"https://www.randomlists.com/img/people/franklin_d_roosevelt.jpg"]);
        Celeb::create(["name"=>"Freddie Mercury","img"=>"https://www.randomlists.com/img/people/freddie_mercury.jpg"]);
        Celeb::create(["name"=>"Frederick Douglass","img"=>"https://www.randomlists.com/img/people/frederick_douglass.jpg"]);
        Celeb::create(["name"=>"Galileo Galilei","img"=>"https://www.randomlists.com/img/people/galileo_galilei.jpg"]);
        Celeb::create(["name"=>"George Bush","img"=>"https://www.randomlists.com/img/people/george_bush.jpg"]);
        Celeb::create(["name"=>"George Clooney","img"=>"https://www.randomlists.com/img/people/george_clooney.jpg"]);
        Celeb::create(["name"=>"George Harrison","img"=>"https://www.randomlists.com/img/people/george_harrison.jpg"]);
        Celeb::create(["name"=>"George Lucas","img"=>"https://www.randomlists.com/img/people/george_lucas.jpg"]);
        Celeb::create(["name"=>"George S. Patton","img"=>"https://www.randomlists.com/img/people/george_s_patton.jpg"]);
        Celeb::create(["name"=>"George Washington","img"=>"https://www.randomlists.com/img/people/george_washington.jpg"]);
        Celeb::create(["name"=>"Glenn Beck","img"=>"https://www.randomlists.com/img/people/glenn_beck.jpg"]);
        Celeb::create(["name"=>"Harriet Tubman","img"=>"https://www.randomlists.com/img/people/harriet_tubman.jpg"]);
        Celeb::create(["name"=>"Harrison Ford","img"=>"https://www.randomlists.com/img/people/harrison_ford.jpg"]);
        Celeb::create(["name"=>"Harry Houdini","img"=>"https://www.randomlists.com/img/people/harry_houdini.jpg"]);
        Celeb::create(["name"=>"Harry S. Truman","img"=>"https://www.randomlists.com/img/people/harry_s_truman.jpg"]);
        Celeb::create(["name"=>"Heidi Klum","img"=>"https://www.randomlists.com/img/people/heidi_klum.jpg"]);
        Celeb::create(["name"=>"Helen Keller","img"=>"https://www.randomlists.com/img/people/helen_keller.jpg"]);
        Celeb::create(["name"=>"Henry Kissinger","img"=>"https://www.randomlists.com/img/people/henry_kissinger.jpg"]);
        Celeb::create(["name"=>"Homer","img"=>"https://www.randomlists.com/img/people/homer.jpg"]);
        Celeb::create(["name"=>"Howard Stern","img"=>"https://www.randomlists.com/img/people/howard_stern.jpg"]);
        Celeb::create(["name"=>"Hugh Laurie","img"=>"https://www.randomlists.com/img/people/hugh_laurie.jpg"]);
        Celeb::create(["name"=>"Hulk Hogan","img"=>"https://www.randomlists.com/img/people/hulk_hogan.jpg"]);
        Celeb::create(["name"=>"Hunter S. Thompson","img"=>"https://www.randomlists.com/img/people/hunter_s_thompson.jpg"]);
        Celeb::create(["name"=>"James Cameron","img"=>"https://www.randomlists.com/img/people/james_cameron.jpg"]);
        Celeb::create(["name"=>"James Dean","img"=>"https://www.randomlists.com/img/people/james_dean.jpg"]);
        Celeb::create(["name"=>"James Earl Jones","img"=>"https://www.randomlists.com/img/people/james_earl_jones.jpg"]);
        Celeb::create(["name"=>"James Madison","img"=>"https://www.randomlists.com/img/people/james_madison.jpg"]);
        Celeb::create(["name"=>"James Patterson","img"=>"https://www.randomlists.com/img/people/james_patterson.jpg"]);
        Celeb::create(["name"=>"James Stewart","img"=>"https://www.randomlists.com/img/people/james_stewart.jpg"]);
        Celeb::create(["name"=>"Jay Leno","img"=>"https://www.randomlists.com/img/people/jay_leno.jpg"]);
        Celeb::create(["name"=>"Jay-Z","img"=>"https://www.randomlists.com/img/people/jay_z.jpg"]);
        Celeb::create(["name"=>"Jeff Dunham","img"=>"https://www.randomlists.com/img/people/jeff_dunham.jpg"]);
        Celeb::create(["name"=>"Jeff Gordon","img"=>"https://www.randomlists.com/img/people/jeff_gordon.jpg"]);
        Celeb::create(["name"=>"Jennifer Aniston","img"=>"https://www.randomlists.com/img/people/jennifer_aniston.jpg"]);
        Celeb::create(["name"=>"Jennifer Lopez","img"=>"https://www.randomlists.com/img/people/jennifer_lopez.jpg"]);
        Celeb::create(["name"=>"Jennifer Love Hewitt","img"=>"https://www.randomlists.com/img/people/jennifer_love_hewitt.jpg"]);
        Celeb::create(["name"=>"Jerry Bruckheimer","img"=>"https://www.randomlists.com/img/people/jerry_bruckheimer.jpg"]);
        Celeb::create(["name"=>"Jerry Seinfeld","img"=>"https://www.randomlists.com/img/people/jerry_seinfeld.jpg"]);
        Celeb::create(["name"=>"Jesse Jackson","img"=>"https://www.randomlists.com/img/people/jesse_jackson.jpg"]);
        Celeb::create(["name"=>"Jesus Christ","img"=>"https://www.randomlists.com/img/people/jesus_christ.jpg"]);
        Celeb::create(["name"=>"Jim Carrey","img"=>"https://www.randomlists.com/img/people/jim_carrey.jpg"]);
        Celeb::create(["name"=>"Joe Montana","img"=>"https://www.randomlists.com/img/people/joe_montana.jpg"]);
        Celeb::create(["name"=>"John F. Kennedy","img"=>"https://www.randomlists.com/img/people/john_f_kennedy.jpg"]);
        Celeb::create(["name"=>"John Lennon","img"=>"https://www.randomlists.com/img/people/john_lennon.jpg"]);
        Celeb::create(["name"=>"John the Baptist","img"=>"https://www.randomlists.com/img/people/john_the_baptist.jpg"]);
        Celeb::create(["name"=>"John Wayne","img"=>"https://www.randomlists.com/img/people/john_wayne.jpg"]);
        Celeb::create(["name"=>"Johnny Cash","img"=>"https://www.randomlists.com/img/people/johnny_cash.jpg"]);
        Celeb::create(["name"=>"Johnny Depp","img"=>"https://www.randomlists.com/img/people/johnny_depp.jpg"]);
        Celeb::create(["name"=>"Jon Stewart","img"=>"https://www.randomlists.com/img/people/jon_stewart.jpg"]);
        Celeb::create(["name"=>"Julia Roberts","img"=>"https://www.randomlists.com/img/people/julia_roberts.jpg"]);
        Celeb::create(["name"=>"Julius Caesar","img"=>"https://www.randomlists.com/img/people/julius_caesar.jpg"]);
        Celeb::create(["name"=>"Justin Bieber","img"=>"https://www.randomlists.com/img/people/justin_bieber.jpg"]);
        Celeb::create(["name"=>"Justin Timberlake","img"=>"https://www.randomlists.com/img/people/justin_timberlake.jpg"]);
        Celeb::create(["name"=>"Kanye West","img"=>"https://www.randomlists.com/img/people/kanye_west.jpg"]);
        Celeb::create(["name"=>"Kareem Abdul-Jabbar","img"=>"https://www.randomlists.com/img/people/kareem_abdul_jabbar.jpg"]);
        Celeb::create(["name"=>"Karl Marx","img"=>"https://www.randomlists.com/img/people/karl_marx.jpg"]);
        Celeb::create(["name"=>"Kate Moss","img"=>"https://www.randomlists.com/img/people/kate_moss.jpg"]);
        Celeb::create(["name"=>"Kate Upton","img"=>"https://www.randomlists.com/img/people/kate_upton.jpg"]);
        Celeb::create(["name"=>"Katharine Hepburn","img"=>"https://www.randomlists.com/img/people/katharine_hepburn.jpg"]);
        Celeb::create(["name"=>"Katherine Heigl","img"=>"https://www.randomlists.com/img/people/katherine_heigl.jpg"]);
        Celeb::create(["name"=>"Katy Perry","img"=>"https://www.randomlists.com/img/people/katy_perry.jpg"]);
        Celeb::create(["name"=>"Keith Richards","img"=>"https://www.randomlists.com/img/people/keith_richards.jpg"]);
        Celeb::create(["name"=>"Kenny Chesney","img"=>"https://www.randomlists.com/img/people/kenny_chesney.jpg"]);
        Celeb::create(["name"=>"Kevin Garnett","img"=>"https://www.randomlists.com/img/people/kevin_garnett.jpg"]);
        Celeb::create(["name"=>"King Arthur","img"=>"https://www.randomlists.com/img/people/king_arthur.jpg"]);
        Celeb::create(["name"=>"Kobe Bryant","img"=>"https://www.randomlists.com/img/people/kobe_bryant.jpg"]);
        Celeb::create(["name"=>"Kristen Bell","img"=>"https://www.randomlists.com/img/people/kristen_bell.jpg"]);
        Celeb::create(["name"=>"Kristen Stewart","img"=>"https://www.randomlists.com/img/people/kristen_stewart.jpg"]);
        Celeb::create(["name"=>"Lady Gaga","img"=>"https://www.randomlists.com/img/people/lady_gaga.jpg"]);
        Celeb::create(["name"=>"Larry David","img"=>"https://www.randomlists.com/img/people/larry_david.jpg"]);
        Celeb::create(["name"=>"Larry the Cable Guy","img"=>"https://www.randomlists.com/img/people/larry_the_cable_guy.jpg"]);
        Celeb::create(["name"=>"LeBron James","img"=>"https://www.randomlists.com/img/people/lebron_james.jpg"]);
        Celeb::create(["name"=>"Leonardo da Vinci","img"=>"https://www.randomlists.com/img/people/leonardo_da_vinci.jpg"]);
        Celeb::create(["name"=>"Leonardo DiCaprio","img"=>"https://www.randomlists.com/img/people/leonardo_dicaprio.jpg"]);
        Celeb::create(["name"=>"Lil Wayne","img"=>"https://www.randomlists.com/img/people/lil_wayne.jpg"]);
        Celeb::create(["name"=>"Liv Tyler","img"=>"https://www.randomlists.com/img/people/liv_tyler.jpg"]);
        Celeb::create(["name"=>"Madonna","img"=>"https://www.randomlists.com/img/people/madonna.jpg"]);
        Celeb::create(["name"=>"Mahatma Gandhi","img"=>"https://www.randomlists.com/img/people/mahatma_gandhi.jpg"]);
        Celeb::create(["name"=>"Manny Pacquiáo","img"=>"https://www.randomlists.com/img/people/manny_pacqui_o.jpg"]);
        Celeb::create(["name"=>"Maria Sharapova","img"=>"https://www.randomlists.com/img/people/maria_sharapova.jpg"]);
        Celeb::create(["name"=>"Marie Antoinette","img"=>"https://www.randomlists.com/img/people/marie_antoinette.jpg"]);
        Celeb::create(["name"=>"Marilyn Monroe","img"=>"https://www.randomlists.com/img/people/marilyn_monroe.jpg"]);
        Celeb::create(["name"=>"Mariska Hargitay","img"=>"https://www.randomlists.com/img/people/mariska_hargitay.jpg"]);
        Celeb::create(["name"=>"Mark Burnett","img"=>"https://www.randomlists.com/img/people/mark_burnett.jpg"]);
        Celeb::create(["name"=>"Mark Harmon","img"=>"https://www.randomlists.com/img/people/mark_harmon.jpg"]);
        Celeb::create(["name"=>"Mark Twain","img"=>"https://www.randomlists.com/img/people/mark_twain.jpg"]);
        Celeb::create(["name"=>"Mark Wahlberg","img"=>"https://www.randomlists.com/img/people/mark_wahlberg.jpg"]);
        Celeb::create(["name"=>"Martin Luther King, Jr.","img"=>"https://www.randomlists.com/img/people/martin_luther_king_jr_.jpg"]);
        Celeb::create(["name"=>"Matthew McConaughey","img"=>"https://www.randomlists.com/img/people/matthew_mcconaughey.jpg"]);
        Celeb::create(["name"=>"Maya Angelou","img"=>"https://www.randomlists.com/img/people/maya_angelou.jpg"]);
        Celeb::create(["name"=>"Mel Blanc","img"=>"https://www.randomlists.com/img/people/mel_blanc.jpg"]);
        Celeb::create(["name"=>"Meriwether Lewis","img"=>"https://www.randomlists.com/img/people/meriwether_lewis.jpg"]);
        Celeb::create(["name"=>"Meryl Streep","img"=>"https://www.randomlists.com/img/people/meryl_streep.jpg"]);
        Celeb::create(["name"=>"Michael Jordan","img"=>"https://www.randomlists.com/img/people/michael_jordan.jpg"]);
        Celeb::create(["name"=>"Miley Cyrus","img"=>"https://www.randomlists.com/img/people/miley_cyrus.jpg"]);
        Celeb::create(["name"=>"Morgan Freeman","img"=>"https://www.randomlists.com/img/people/morgan_freeman.jpg"]);
        Celeb::create(["name"=>"Moses","img"=>"https://www.randomlists.com/img/people/moses.jpg"]);
        Celeb::create(["name"=>"Mother Teresa","img"=>"https://www.randomlists.com/img/people/mother_teresa.jpg"]);
        Celeb::create(["name"=>"Muhammad Ali","img"=>"https://www.randomlists.com/img/people/muhammad_ali.jpg"]);
        Celeb::create(["name"=>"Napoleon Bonaparte","img"=>"https://www.randomlists.com/img/people/napoleon_bonaparte.jpg"]);
        Celeb::create(["name"=>"Natalie Portman","img"=>"https://www.randomlists.com/img/people/natalie_portman.jpg"]);
        Celeb::create(["name"=>"Neil Armstrong","img"=>"https://www.randomlists.com/img/people/neil_armstrong.jpg"]);
        Celeb::create(["name"=>"Neil Diamond","img"=>"https://www.randomlists.com/img/people/neil_diamond.jpg"]);
        Celeb::create(["name"=>"Nicolas Cage","img"=>"https://www.randomlists.com/img/people/nicolas_cage.jpg"]);
        Celeb::create(["name"=>"Nicole Kidman","img"=>"https://www.randomlists.com/img/people/nicole_kidman.jpg"]);
        Celeb::create(["name"=>"Nikola Tesla","img"=>"https://www.randomlists.com/img/people/nikola_tesla.jpg"]);
        Celeb::create(["name"=>"Noah","img"=>"https://www.randomlists.com/img/people/noah.jpg"]);
        Celeb::create(["name"=>"Nostradamus","img"=>"https://www.randomlists.com/img/people/nostradamus.jpg"]);
        Celeb::create(["name"=>"Oprah Winfrey","img"=>"https://www.randomlists.com/img/people/oprah_winfrey.jpg"]);
        Celeb::create(["name"=>"Oscar Wilde","img"=>"https://www.randomlists.com/img/people/oscar_wilde.jpg"]);
        Celeb::create(["name"=>"Pablo Picasso","img"=>"https://www.randomlists.com/img/people/pablo_picasso.jpg"]);
        Celeb::create(["name"=>"Paul McCartney","img"=>"https://www.randomlists.com/img/people/paul_mccartney.jpg"]);
        Celeb::create(["name"=>"Paul Newman","img"=>"https://www.randomlists.com/img/people/paul_newman.jpg"]);
        Celeb::create(["name"=>"Pete Rose","img"=>"https://www.randomlists.com/img/people/pete_rose.jpg"]);
        Celeb::create(["name"=>"Peyton Manning","img"=>"https://www.randomlists.com/img/people/peyton_manning.jpg"]);
        Celeb::create(["name"=>"Phil McGraw","img"=>"https://www.randomlists.com/img/people/phil_mcgraw.jpg"]);
        Celeb::create(["name"=>"Phil Mickelson","img"=>"https://www.randomlists.com/img/people/phil_mickelson.jpg"]);
        Celeb::create(["name"=>"Plato","img"=>"https://www.randomlists.com/img/people/plato.jpg"]);
        Celeb::create(["name"=>"Pope John Paul II","img"=>"https://www.randomlists.com/img/people/pope_john_paul_ii.jpg"]);
        Celeb::create(["name"=>"Prophet Muhammed","img"=>"https://www.randomlists.com/img/people/prophet_muhammed.jpg"]);
        Celeb::create(["name"=>"Queen Latifah","img"=>"https://www.randomlists.com/img/people/queen_latifah.jpg"]);
        Celeb::create(["name"=>"Rachael Ray","img"=>"https://www.randomlists.com/img/people/rachael_ray.jpg"]);
        Celeb::create(["name"=>"Rafael Nadal","img"=>"https://www.randomlists.com/img/people/rafael_nadal.jpg"]);
        Celeb::create(["name"=>"Raoul Wallenberg","img"=>"https://www.randomlists.com/img/people/raoul_wallenberg.jpg"]);
        Celeb::create(["name"=>"Ray Romano","img"=>"https://www.randomlists.com/img/people/ray_romano.jpg"]);
        Celeb::create(["name"=>"Reese Witherspoon","img"=>"https://www.randomlists.com/img/people/reese_witherspoon.jpg"]);
        Celeb::create(["name"=>"Roald Dahl","img"=>"https://www.randomlists.com/img/people/roald_dahl.jpg"]);
        Celeb::create(["name"=>"Robert De Niro","img"=>"https://www.randomlists.com/img/people/robert_de_niro.jpg"]);
        Celeb::create(["name"=>"Robert Downey Jr.","img"=>"https://www.randomlists.com/img/people/robert_downey_jr_.jpg"]);
        Celeb::create(["name"=>"Robert F. Kennedy, Jr.","img"=>"https://www.randomlists.com/img/people/robert_f_kennedy_jr_.jpg"]);
        Celeb::create(["name"=>"Robin Hood","img"=>"https://www.randomlists.com/img/people/robin_hood.jpg"]);
        Celeb::create(["name"=>"Robin Williams","img"=>"https://www.randomlists.com/img/people/robin_williams.jpg"]);
        Celeb::create(["name"=>"Roger Federer","img"=>"https://www.randomlists.com/img/people/roger_federer.jpg"]);
        Celeb::create(["name"=>"Ron Paul","img"=>"https://www.randomlists.com/img/people/ron_paul.jpg"]);
        Celeb::create(["name"=>"Ronald Reagan","img"=>"https://www.randomlists.com/img/people/ronald_reagan.jpg"]);
        Celeb::create(["name"=>"Rush Limbaugh","img"=>"https://www.randomlists.com/img/people/rush_limbaugh.jpg"]);
        Celeb::create(["name"=>"Ryan Reynolds","img"=>"https://www.randomlists.com/img/people/ryan_reynolds.jpg"]);
        Celeb::create(["name"=>"Ryan Seacrest","img"=>"https://www.randomlists.com/img/people/ryan_seacrest.jpg"]);
        Celeb::create(["name"=>"Sandra Bullock","img"=>"https://www.randomlists.com/img/people/sandra_bullock.jpg"]);
        Celeb::create(["name"=>"Sarah Jessica Parker","img"=>"https://www.randomlists.com/img/people/sarah_jessica_parker.jpg"]);
        Celeb::create(["name"=>"Scarlett Johansson","img"=>"https://www.randomlists.com/img/people/scarlett_johansson.jpg"]);
        Celeb::create(["name"=>"Sean Combs","img"=>"https://www.randomlists.com/img/people/sean_combs.jpg"]);
        Celeb::create(["name"=>"Serena Williams","img"=>"https://www.randomlists.com/img/people/serena_williams.jpg"]);
        Celeb::create(["name"=>"Simon Cowell","img"=>"https://www.randomlists.com/img/people/simon_cowell.jpg"]);
        Celeb::create(["name"=>"Socrates","img"=>"https://www.randomlists.com/img/people/socrates.jpg"]);
        Celeb::create(["name"=>"Stephenie Meyer","img"=>"https://www.randomlists.com/img/people/stephenie_meyer.jpg"]);
        Celeb::create(["name"=>"Stephen Hawking","img"=>"https://www.randomlists.com/img/people/stephen_hawking.jpg"]);
        Celeb::create(["name"=>"Stephen King","img"=>"https://www.randomlists.com/img/people/stephen_king.jpg"]);
        Celeb::create(["name"=>"Steve Carell","img"=>"https://www.randomlists.com/img/people/steve_carell.jpg"]);
        Celeb::create(["name"=>"Steve Jobs","img"=>"https://www.randomlists.com/img/people/steve_jobs.jpg"]);
        Celeb::create(["name"=>"Steven Spielberg","img"=>"https://www.randomlists.com/img/people/steven_spielberg.jpg"]);
        Celeb::create(["name"=>"Summer Glau","img"=>"https://www.randomlists.com/img/people/summer_glau.jpg"]);
        Celeb::create(["name"=>"Taylor Swift","img"=>"https://www.randomlists.com/img/people/taylor_swift.jpg"]);
        Celeb::create(["name"=>"Teri Hatcher","img"=>"https://www.randomlists.com/img/people/teri_hatcher.jpg"]);
        Celeb::create(["name"=>"The Rock","img"=>"https://www.randomlists.com/img/people/the_rock.jpg"]);
        Celeb::create(["name"=>"Theodore Roosevelt","img"=>"https://www.randomlists.com/img/people/theodore_roosevelt.jpg"]);
        Celeb::create(["name"=>"Thomas Edison","img"=>"https://www.randomlists.com/img/people/thomas_edison.jpg"]);
        Celeb::create(["name"=>"Thomas Jefferson","img"=>"https://www.randomlists.com/img/people/thomas_jefferson.jpg"]);
        Celeb::create(["name"=>"Tiger Woods","img"=>"https://www.randomlists.com/img/people/tiger_woods.jpg"]);
        Celeb::create(["name"=>"Tim McGraw","img"=>"https://www.randomlists.com/img/people/tim_mcgraw.jpg"]);
        Celeb::create(["name"=>"Tina Fey","img"=>"https://www.randomlists.com/img/people/tina_fey.jpg"]);
        Celeb::create(["name"=>"Toby Keith","img"=>"https://www.randomlists.com/img/people/toby_keith.jpg"]);
        Celeb::create(["name"=>"Tom Brady","img"=>"https://www.randomlists.com/img/people/tom_brady.jpg"]);
        Celeb::create(["name"=>"Tom Cruise","img"=>"https://www.randomlists.com/img/people/tom_cruise.jpg"]);
        Celeb::create(["name"=>"Tom Hanks","img"=>"https://www.randomlists.com/img/people/tom_hanks.jpg"]);
        Celeb::create(["name"=>"Tyler Perry","img"=>"https://www.randomlists.com/img/people/tyler_perry.jpg"]);
        Celeb::create(["name"=>"Ulysses S. Grant","img"=>"https://www.randomlists.com/img/people/ulysses_s_grant.jpg"]);
        Celeb::create(["name"=>"Usain Bolt","img"=>"https://www.randomlists.com/img/people/usain_bolt.jpg"]);
        Celeb::create(["name"=>"Usher","img"=>"https://www.randomlists.com/img/people/usher.jpg"]);
        Celeb::create(["name"=>"Venus Williams","img"=>"https://www.randomlists.com/img/people/venus_williams.jpg"]);
        Celeb::create(["name"=>"Vince Lombardi","img"=>"https://www.randomlists.com/img/people/vince_lombardi.jpg"]);
        Celeb::create(["name"=>"Voltaire","img"=>"https://www.randomlists.com/img/people/voltaire.jpg"]);
        Celeb::create(["name"=>"Walt Disney","img"=>"https://www.randomlists.com/img/people/walt_disney.jpg"]);
        Celeb::create(["name"=>"Walt Whitman","img"=>"https://www.randomlists.com/img/people/walt_whitman.jpg"]);
        Celeb::create(["name"=>"Will Smith","img"=>"https://www.randomlists.com/img/people/will_smith.jpg"]);
        Celeb::create(["name"=>"William Shakespeare","img"=>"https://www.randomlists.com/img/people/william_shakespeare.jpg"]);
        Celeb::create(["name"=>"William Shatner","img"=>"https://www.randomlists.com/img/people/william_shatner.jpg"]);
        Celeb::create(["name"=>"William Wallace","img"=>"https://www.randomlists.com/img/people/william_wallace.jpg"]);
        Celeb::create(["name"=>"Winston Churchill","img"=>"https://www.randomlists.com/img/people/winston_churchill.jpg"]);
        Celeb::create(["name"=>"Wolfgang Puck","img"=>"https://www.randomlists.com/img/people/wolfgang_puck.jpg"]);
    }
}
